dist: trusty
sudo: require

language: cpp
os: linux
compiler: gcc

#Disable the default Travis submodule behavior.
git:
  submodules: false

addons:
  apt:
    packages:
      - gcc
      - g++

# Safelist - branches to be built.
branches:
  only:
  - master

before_script:
  # create a build folder for the out-of-source build
  - mkdir build
  # switch to build directory
  - cd build
  # Install the development librairies and headers for freeglut3
  - sudo apt-get install freeglut3-dev -y --force-yes
  # Install the Xrandr used by SFML to set the size, orientation and/or reflection of the outputs for a screen. It can also set the screen size.
  - sudo apt-get install libxrandr-dev -y --force-yes
  - sudo apt-get install libxinerama-dev -y --force-yes
  - sudo apt-get install libxcursor-dev -y --force-yes
  # Install the UDev library used by SFML
  - sudo apt-get install libudev-dev -y --force-yes
  # run cmake; here we assume that the project's
  # top-level CMakeLists.txt is located at '..'
  - cmake ..

script:
  - VERBOSE=1 make
  - make
  - make CODEFRAME_TESTS