# This is a sample build configuration for C++ – Make.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: gcc:6.5

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          # Print the Linux version.
          - uname -a
          # Print the gcc version.
          - gcc --version
          #  Install a CMake 3.0.2 version.
          #- apt-get update -qq
          #- apt-get install cmake -y
          #  Alternatively you could install a CMake 3.2.2 version through PPA repository. 
          - apt-get update -qq
          - apt-get install software-properties-common -y
          # Add PPA repository.
          - echo 'deb http://ppa.launchpad.net/george-edison55/cmake-3.x/ubuntu trusty main' | tee -a /etc/apt/sources.list.d/cmake.list
          - apt-get update -qq
          - apt-get install cmake -y --force-yes
          # Install the development librairies and headers for freeglut3
          - apt-get install freeglut3-dev -y --force-yes
          # Install the Xrandr used by SFML to set the size, orientation and/or reflection of the outputs for a screen. It can also set the screen size.
          - apt-get install x11-xserver-utils -y --force-yes
          # Print the CMake version.
          - cmake --version  
          - mkdir build
          - cd build
          # Call the CMake.
          - cmake ..
          # Build the project.
          - make