#ifndef SERIALIZABLEPROPERTYTABLE_HPP_INCLUDED
#define SERIALIZABLEPROPERTYTABLE_HPP_INCLUDED

#include "typeinterface.hpp"

namespace codeframe
{

}

#endif // SERIALIZABLEPROPERTYTABLE_HPP_INCLUDED
