#ifndef SERIALIZABLESRC_GLOBAL_H
#define SERIALIZABLESRC_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SERIALIZABLESRC_LIBRARY)
#  define SERIALIZABLESRCSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SERIALIZABLESRCSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SERIALIZABLESRC_GLOBAL_H
