#ifndef PERFORMANCEAPPLICATIONDEF_HPP_INCLUDED
#define PERFORMANCEAPPLICATIONDEF_HPP_INCLUDED

#define PERFORMANCE_LOAD_XML_FILE 1
#define PERFORMANCE_BOX2D_FULL_PHYSIC_SYM 2
#define PERFORMANCE_RENDER_GRAPHIC 3
#define PERFORMANCE_BOX2D_ONLY_PHYSIC_SYM 4
#define PERFORMANCE_BOX2D_RAYS_CAST 5
#define PERFORMANCE_CALCULATE_NEURONS 6
#define PERFORMANCE_SAVE_XML_FILE 7

#endif // PERFORMANCEAPPLICATIONDEF_HPP_INCLUDED
